//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexaSkill.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int Id { get; set; }
        public byte[] Title { get; set; }
        public byte[] Author { get; set; }
        public string Content { get; set; }
        public int Votes { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
